spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:h2:mem:transactiondb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8083

# For local development
aws:
  paramstore:
    enabled: false
  region: eu-central-1
