spring:
  application:
    name: banking-service
  datasource:
    url: jdbc:h2:mem:bankingdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

# For local development
aws:
  paramstore:
    enabled: false
  region: eu-central-1

# Plaid configuration (for local development)
plaid:
  client-id: test-client-id
  secret: test-secret
  environment: sandbox
