server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking-user-db
    username: hrvojevincek
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka